stages:
  clean-data:
    cmd: podman run -w /root/code --rm --mount type=bind,src=$PWD,dst=/root docker.io/eamon/2019measles:v20200928
      Rscript fetch-clean-data.R
    deps:
    - code/fetch-clean-data.R
    - data/raw-data
    outs:
    - data/clean-data
  construct-fitting-pomps:
    cmd: podman run -w /root/code --rm --mount type=bind,src=$PWD,dst=/root docker.io/eamon/2019measles:v20200928
      Rscript define-continuous-measles-pomp.R
    deps:
    - code/define-continuous-measles-pomp.R
    - data/clean-data
    outs:
    - code/measles-pomp-object-Agadez.RDS
    - code/measles-pomp-object-Maradi.RDS
    - code/measles-pomp-object-Niamey.RDS
    - code/measles-pomp-object-Zinder.RDS
  simulate-for-emergence-ews:
    cmd: podman run -w /root/code --rm --mount type=bind,src=$PWD,dst=/root docker.io/eamon/2019measles:v20200928
      Rscript simulate-emergence-grid.R
    deps:
    - code/make-pomp-simulator-function.R
    - code/measles-pomp-object-Agadez.RDS
    - code/measles-pomp-object-Maradi.RDS
    - code/measles-pomp-object-Niamey.RDS
    - code/measles-pomp-object-Zinder.RDS
    - code/simulate-emergence-grid.R
    - results/initial-mif-lls-Agadez.csv
    - results/initial-mif-lls-Maradi.csv
    - results/initial-mif-lls-Niamey.csv
    - results/initial-mif-lls-Zinder.csv
    outs:
    - simulations/emergence-simulations-grid-Agadez-0.1.RDS
    - simulations/emergence-simulations-grid-Agadez-0.2.RDS
    - simulations/emergence-simulations-grid-Agadez-0.3.RDS
    - simulations/emergence-simulations-grid-Agadez-0.4.RDS
    - simulations/emergence-simulations-grid-Agadez-0.5.RDS
    - simulations/emergence-simulations-grid-Agadez-0.6.RDS
    - simulations/emergence-simulations-grid-Agadez-0.7.RDS
    - simulations/emergence-simulations-grid-Agadez-0.8.RDS
    - simulations/emergence-simulations-grid-Agadez-0.9.RDS
    - simulations/emergence-simulations-grid-Agadez-1.RDS
    - simulations/emergence-simulations-grid-Agadez-1e-04.RDS
    - simulations/emergence-simulations-grid-Maradi-0.1.RDS
    - simulations/emergence-simulations-grid-Maradi-0.2.RDS
    - simulations/emergence-simulations-grid-Maradi-0.3.RDS
    - simulations/emergence-simulations-grid-Maradi-0.4.RDS
    - simulations/emergence-simulations-grid-Maradi-0.5.RDS
    - simulations/emergence-simulations-grid-Maradi-0.6.RDS
    - simulations/emergence-simulations-grid-Maradi-0.7.RDS
    - simulations/emergence-simulations-grid-Maradi-0.8.RDS
    - simulations/emergence-simulations-grid-Maradi-0.9.RDS
    - simulations/emergence-simulations-grid-Maradi-1.RDS
    - simulations/emergence-simulations-grid-Maradi-1e-04.RDS
    - simulations/emergence-simulations-grid-Niamey-0.1.RDS
    - simulations/emergence-simulations-grid-Niamey-0.2.RDS
    - simulations/emergence-simulations-grid-Niamey-0.3.RDS
    - simulations/emergence-simulations-grid-Niamey-0.4.RDS
    - simulations/emergence-simulations-grid-Niamey-0.5.RDS
    - simulations/emergence-simulations-grid-Niamey-0.6.RDS
    - simulations/emergence-simulations-grid-Niamey-0.7.RDS
    - simulations/emergence-simulations-grid-Niamey-0.8.RDS
    - simulations/emergence-simulations-grid-Niamey-0.9.RDS
    - simulations/emergence-simulations-grid-Niamey-1.RDS
    - simulations/emergence-simulations-grid-Niamey-1e-04.RDS
    - simulations/emergence-simulations-grid-Zinder-0.1.RDS
    - simulations/emergence-simulations-grid-Zinder-0.2.RDS
    - simulations/emergence-simulations-grid-Zinder-0.3.RDS
    - simulations/emergence-simulations-grid-Zinder-0.4.RDS
    - simulations/emergence-simulations-grid-Zinder-0.5.RDS
    - simulations/emergence-simulations-grid-Zinder-0.6.RDS
    - simulations/emergence-simulations-grid-Zinder-0.7.RDS
    - simulations/emergence-simulations-grid-Zinder-0.8.RDS
    - simulations/emergence-simulations-grid-Zinder-0.9.RDS
    - simulations/emergence-simulations-grid-Zinder-1.RDS
    - simulations/emergence-simulations-grid-Zinder-1e-04.RDS
  analyze-emergence-ews:
    cmd: podman run -w /root/code --rm --mount type=bind,src=$PWD,dst=/root docker.io/eamon/2019measles:v20200928
      Rscript analyze-emergence-grid-sims.R
    deps:
    - code/analyze-emergence-grid-sims.R
    - simulations/emergence-simulations-grid-Agadez-0.1.RDS
    - simulations/emergence-simulations-grid-Agadez-0.2.RDS
    - simulations/emergence-simulations-grid-Agadez-0.3.RDS
    - simulations/emergence-simulations-grid-Agadez-0.4.RDS
    - simulations/emergence-simulations-grid-Agadez-0.5.RDS
    - simulations/emergence-simulations-grid-Agadez-1e-04.RDS
    - simulations/emergence-simulations-grid-Maradi-0.1.RDS
    - simulations/emergence-simulations-grid-Maradi-0.2.RDS
    - simulations/emergence-simulations-grid-Maradi-0.3.RDS
    - simulations/emergence-simulations-grid-Maradi-0.4.RDS
    - simulations/emergence-simulations-grid-Maradi-0.5.RDS
    - simulations/emergence-simulations-grid-Maradi-1e-04.RDS
    - simulations/emergence-simulations-grid-Niamey-0.1.RDS
    - simulations/emergence-simulations-grid-Niamey-0.2.RDS
    - simulations/emergence-simulations-grid-Niamey-0.3.RDS
    - simulations/emergence-simulations-grid-Niamey-0.4.RDS
    - simulations/emergence-simulations-grid-Niamey-0.5.RDS
    - simulations/emergence-simulations-grid-Niamey-1e-04.RDS
    - simulations/emergence-simulations-grid-Zinder-0.1.RDS
    - simulations/emergence-simulations-grid-Zinder-0.2.RDS
    - simulations/emergence-simulations-grid-Zinder-0.3.RDS
    - simulations/emergence-simulations-grid-Zinder-0.4.RDS
    - simulations/emergence-simulations-grid-Zinder-0.5.RDS
    - simulations/emergence-simulations-grid-Zinder-1e-04.RDS
    outs:
    - results/emergence-bandwidths.csv
    - results/emergence-grid-aucs.csv
    - results/ews-emergence.csv
