---
title: "Inhibition estimate to characterize vaccination regime"
output: html_notebook
---

This notebook reproduces the simulations that are done for calculation of early warning signals in `simulate-elimination-grid.R`. The several plots and calculations are added to provide insight into why some early warning signals perform poorly and some new, better performing, indicators are calculated.

```{r}

# Define function for vaccination campaign --------------------------------

rho_curve_ramp <- function(t, start = 52*4, speed = 0.0015){
  ifelse(
    t <= start,
    rho <- 0.7,
    rho <- min(0.7 + (t - start)*speed, 1)  # linear
  )
  return(rho)
}


# Set up grid of vaccination roll out speeds ------------------------------


speed_grid <- seq(0.000015, 0.0001, length.out = 6)  # linear


# Load libraries ----------------------------------------------------------

library(tidyverse)
library(pomp)
library(foreach)
library(doParallel)  # functions for parallel computing

if(parallel::detectCores() <= length(speed_grid)){
  registerDoParallel(cores = detectCores() - 1)
} else{
  registerDoParallel(cores = length(speed_grid))
}

source("make-pomp-simulator-function.R")
cities <- c("Agadez", "Maradi", "Niamey", "Zinder")
sims <- list()
for(do_city in cities){
  
  # Load fitted parameters and pomp model -----------------------------------
  
  mle_file <- paste0("../results/initial-mif-lls-", do_city, ".csv")
  mles <- read.csv(mle_file) %>% 
    slice(2:n()) %>%  # ignore first row of storage NAs
    filter(loglik == max(loglik, na.rm = TRUE)) %>%
    dplyr::select(-do_grid, -loglik, -loglik_se)
  
  pomp_file <- paste0("./measles-pomp-object-", do_city, ".RDS")
  fitted_pomp <- readRDS(pomp_file)
  N1 <- round(mean(fitted_pomp@covar[, "N"]))
  
  # Simulate from the new pomp object ---------------------------------------
  
  temp_res <- list()
  outsims <- foreach(i = speed_grid,
                     .packages = c("pomp", "tidyverse", "dplyr"), 
                     .combine = "rbind") %do%
  {
    years <- 100
    weeks <- years*52
    days <- years*365
    vacc_coverage_ts <- sapply(0:days, FUN = rho_curve_ramp, 
                               start = 50*365, speed = i)

    simulator_pomp <- make_pomp_simulator(
      do_city, 
      mles, 
      years_to_sim = years, 
      initial_population_size = N1, 
      susc_discount = 1,
      exposed_discount = 1,
      infected_discount = 1,
      vacc_coverage_ts = vacc_coverage_ts
    )
    
    temp_res[[as.character(i)]] <- simulate(
      simulator_pomp,
      nsim = 5,
      as.data.frame = TRUE,
      include.data = FALSE,
      seed = 172856) %>%
      as_tibble() %>% 
      mutate(R0_seas = RE_seas / S * N1) %>% 
      mutate(wstop = min(time[vacc_discount <= 1 / max(R0_seas)])) %>% 
      mutate(wstart = 2 * 50 - wstop) %>%
      mutate(vacc_coverage = 1 - vacc_discount) %>%
      select(-vacc_discount, -starts_with("xi")) %>% 
      group_by(sim) %>% nest()

  }
  sims[[do_city]] <- bind_rows(temp_res, .id = "speed")
}
sims <- bind_rows(sims, .id = "city")

```


```{r fit_S_model}

sim_model <- function(df){
  stats::loess(S ~ time, span = 52 / (nrow(df) * 2), data = df)
}

simfit <- sims %>% mutate(model = purrr::map(data, sim_model))

simfit <- simfit %>% 
  mutate(pred = purrr::map2(data, model, modelr::add_predictions))

preds <- unnest(simfit, pred)

preds %>% filter(sim == 2 & time < 10) %>% 
  ggplot(aes(x = time, y = S)) + geom_point(size = 1, alpha = 0.5) + 
  geom_line(aes(y = pred)) + 
  facet_grid(city ~ as.numeric(speed), scales = "free_y")

```

```{r calc_ieps}

iepsum <- function(df){
  sdrop <- diff(df$pred) < 0
  is_epi <- c(FALSE, sdrop)
  epirle <- rle(is_epi)
  is_scrap <- epirle$lengths[!epirle$values] < 5
  epirle$values[!epirle$values][is_scrap] <- TRUE 
  epirle$values[!epirle$values] <- 1 + seq(1, sum(!epirle$values))
  iepids <- inverse.rle(epirle)
  
  miep <- max(iepids)
  splt <- split(df$S, iepids)
  splt_time <- split(df$time, iepids)
  trimsplt <- splt[-miep][-1]
  trimsplt_time <- splt_time[-miep][-1]
  
  iep_lens <- sapply(trimsplt, length)
  iep_s0 <- sapply(trimsplt, "[", 1)
  iep_sfin <- mapply(function(x, y) x[y], x = trimsplt, y = iep_lens)
  iep_t0 <- sapply(trimsplt_time, "[[", 1)
  iep_tfin <- mapply(function(x, y) x[y], x = trimsplt_time, y = iep_lens)
  epi_sizes <- c(iep_sfin[-length(iep_lens)] - iep_s0[-1], NA)
  ts <- df %>% select(time, S, I, R0_seas) %>% mutate(iepids = iepids)
  iepsum <- tibble(iepid = names(trimsplt), s0 = iep_s0, sfin = iep_sfin, 
                   t0 = iep_t0, tfin = iep_tfin, iep_weeks = iep_lens, 
                   epi_sizes = epi_sizes)
  list(augts = ts, iepsum = iepsum)
}

iepsumout <- purrr::map(simfit$pred, iepsum)
simfit2 <- add_column(simfit, iepts = purrr::map(iepsumout, "augts")) %>%
  add_column(iepsum = purrr::map(iepsumout, "iepsum"))


simfitred <- simfit2 %>% filter(sim == 2 & as.numeric(speed) < 5e-5)
preds <- unnest(simfitred, pred) %>% filter(time < 10)
simsum <- unnest(simfitred, iepsum) %>% filter(tfin < 10)

ggplot(preds, aes(x = time, y = S)) + 
  geom_point() + 
  geom_line(aes(y = pred), col = "red") + 
  geom_rect(data = simsum, 
            aes(xmin = t0, xmax = tfin, group = iepid), 
            inherit.aes = FALSE, ymin = -Inf, ymax = Inf,
            fill = "grey", alpha = .2) + 
  facet_grid(city ~ as.numeric(speed), scales = "free_y") + 
  theme_classic()

```
